name: "Update Changelog"

on:
  release:
    types: [released]

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update CHANGELOG"
          branch: changelog/update-${{ github.event.release.tag_name }}
          title: "Update CHANGELOG for ${{ github.event.release.tag_name }}"
          body: "This PR updates the changelog for ${{ github.event.release.tag_name }}"
          base: main
